export const runtimeModelVariantUrls = new Map<string, string>([
  [
    "/assets/models/manual/dimensiva-beyla-shoe-cabinet-by-kave-home.optimized.glb",
    "/assets/generated/runtime-variants/beyla-shoe-cabinet-runtime-lite.glb"
  ],
  [
    "/assets/models/manual/dimensiva-eames-armchair-rocker-rar-by-vitra.optimized.glb",
    "/assets/generated/runtime-variants/eames-armchair-runtime-lite.glb"
  ],
  [
    "/assets/models/manual/dimensiva-hackney-sofa-by-hay.optimized.glb",
    "/assets/generated/runtime-variants/hackney-sofa-runtime-lite.glb"
  ],
  [
    "/assets/models/manual/dimensiva-ibiza-forte-coffee-table-by-ritzwell.optimized.glb",
    "/assets/generated/runtime-variants/ibiza-coffee-table-runtime-lite.glb"
  ],
  [
    "/assets/models/manual/dimensiva-lotus-vase-by-101-copenhagen.optimized.glb",
    "/assets/generated/runtime-variants/lotus-vase-runtime-lite.glb"
  ],
  [
    "/assets/models/manual/dimensiva-plan-chair-by-fredericia.optimized.glb",
    "/assets/generated/runtime-variants/plan-chair-runtime-lite.glb"
  ],
  [
    "/assets/models/manual/dimensiva-slit-side-table-round-high-by-hay.optimized.glb",
    "/assets/generated/runtime-variants/slit-side-table-runtime-lite.glb"
  ],
  [
    "/assets/models/manual/dimensiva-toio-led-floor-lamp-by-flos.optimized.glb",
    "/assets/generated/runtime-variants/toio-floor-lamp-runtime-lite.glb"
  ],
  [
    "/assets/models/manual/zeel-by-furniture-blown-armchair.optimized.glb",
    "/assets/generated/runtime-variants/blown-armchair-runtime-lite.glb"
  ],
  [
    "/assets/models/manual/zeel-by-furniture-rounded-commode.optimized.glb",
    "/assets/generated/runtime-variants/rounded-commode-runtime-lite.glb"
  ],
  [
    "/assets/models/polyhaven/book_encyclopedia_set_01.optimized.glb",
    "/assets/generated/runtime-variants/book-encyclopedia-set-runtime-lite.glb"
  ],
  [
    "/assets/models/polyhaven/potted_plant_01.optimized.glb",
    "/assets/generated/runtime-variants/potted-plant-01-runtime-lite.glb"
  ],
  [
    "/assets/models/polyhaven/vintage_cabinet_01.optimized.glb",
    "/assets/generated/runtime-variants/vintage-cabinet-runtime-lite.glb"
  ]
])
