export const ktx2RuntimeTextureVariants = new Map<string, string>([
  [
    "/assets/textures-runtime/floors/Carpet016/Carpet016_1K-JPG_AmbientOcclusion.jpg",
    "/assets/textures-runtime-ktx2/floors/Carpet016/Carpet016_1K-JPG_AmbientOcclusion.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/Carpet016/Carpet016_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/floors/Carpet016/Carpet016_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/Carpet016/Carpet016_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/floors/Carpet016/Carpet016_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/Carpet016/Carpet016_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/floors/Carpet016/Carpet016_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/Carpet016/Carpet016_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/floors/Carpet016/Carpet016_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/Carpet016/Carpet016_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/floors/Carpet016/Carpet016_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/Concrete047A/Concrete047A_1K-JPG_AmbientOcclusion.jpg",
    "/assets/textures-runtime-ktx2/floors/Concrete047A/Concrete047A_1K-JPG_AmbientOcclusion.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/Concrete047A/Concrete047A_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/floors/Concrete047A/Concrete047A_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/Concrete047A/Concrete047A_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/floors/Concrete047A/Concrete047A_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/Concrete047A/Concrete047A_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/floors/Concrete047A/Concrete047A_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/Concrete047A/Concrete047A_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/floors/Concrete047A/Concrete047A_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/Concrete047A/Concrete047A_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/floors/Concrete047A/Concrete047A_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/Concrete048/Concrete048_1K-JPG_AmbientOcclusion.jpg",
    "/assets/textures-runtime-ktx2/floors/Concrete048/Concrete048_1K-JPG_AmbientOcclusion.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/Concrete048/Concrete048_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/floors/Concrete048/Concrete048_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/Concrete048/Concrete048_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/floors/Concrete048/Concrete048_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/Concrete048/Concrete048_1K-JPG_Metalness.jpg",
    "/assets/textures-runtime-ktx2/floors/Concrete048/Concrete048_1K-JPG_Metalness.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/Concrete048/Concrete048_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/floors/Concrete048/Concrete048_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/Concrete048/Concrete048_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/floors/Concrete048/Concrete048_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/Concrete048/Concrete048_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/floors/Concrete048/Concrete048_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor007/WoodFloor007_1K-JPG_AmbientOcclusion.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor007/WoodFloor007_1K-JPG_AmbientOcclusion.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor007/WoodFloor007_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor007/WoodFloor007_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor007/WoodFloor007_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor007/WoodFloor007_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor007/WoodFloor007_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor007/WoodFloor007_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor007/WoodFloor007_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor007/WoodFloor007_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor007/WoodFloor007_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor007/WoodFloor007_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor051/WoodFloor051_1K-JPG_AmbientOcclusion.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor051/WoodFloor051_1K-JPG_AmbientOcclusion.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor051/WoodFloor051_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor051/WoodFloor051_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor051/WoodFloor051_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor051/WoodFloor051_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor051/WoodFloor051_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor051/WoodFloor051_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor051/WoodFloor051_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor051/WoodFloor051_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor051/WoodFloor051_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor051/WoodFloor051_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor062/WoodFloor062_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor062/WoodFloor062_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor062/WoodFloor062_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor062/WoodFloor062_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor062/WoodFloor062_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor062/WoodFloor062_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor062/WoodFloor062_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor062/WoodFloor062_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor062/WoodFloor062_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor062/WoodFloor062_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor064/WoodFloor064_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor064/WoodFloor064_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor064/WoodFloor064_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor064/WoodFloor064_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor064/WoodFloor064_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor064/WoodFloor064_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor064/WoodFloor064_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor064/WoodFloor064_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor064/WoodFloor064_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor064/WoodFloor064_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor069/WoodFloor069_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor069/WoodFloor069_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor069/WoodFloor069_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor069/WoodFloor069_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor069/WoodFloor069_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor069/WoodFloor069_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor069/WoodFloor069_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor069/WoodFloor069_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor069/WoodFloor069_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor069/WoodFloor069_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor070/WoodFloor070_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor070/WoodFloor070_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor070/WoodFloor070_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor070/WoodFloor070_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor070/WoodFloor070_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor070/WoodFloor070_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor070/WoodFloor070_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor070/WoodFloor070_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor070/WoodFloor070_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor070/WoodFloor070_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor071/WoodFloor071_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor071/WoodFloor071_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor071/WoodFloor071_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor071/WoodFloor071_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor071/WoodFloor071_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor071/WoodFloor071_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor071/WoodFloor071_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor071/WoodFloor071_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/floors/WoodFloor071/WoodFloor071_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/floors/WoodFloor071/WoodFloor071_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/painted-plaster-017/PaintedPlaster017_2K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/painted-plaster-017/PaintedPlaster017_2K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/painted-plaster-017/PaintedPlaster017_2K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/painted-plaster-017/PaintedPlaster017_2K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/painted-plaster-017/PaintedPlaster017_2K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/painted-plaster-017/PaintedPlaster017_2K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/painted-plaster-017/PaintedPlaster017_2K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/painted-plaster-017/PaintedPlaster017_2K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/painted-plaster-017/PaintedPlaster017_2K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/painted-plaster-017/PaintedPlaster017_2K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-bi-stretch-runner/ao.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-bi-stretch-runner/ao.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-bi-stretch-runner/color.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-bi-stretch-runner/color.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-bi-stretch-runner/displacement.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-bi-stretch-runner/displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-bi-stretch-runner/normal.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-bi-stretch-runner/normal.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-bi-stretch-runner/roughness.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-bi-stretch-runner/roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-caban-boucle-rug/ao.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-caban-boucle-rug/ao.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-caban-boucle-rug/color.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-caban-boucle-rug/color.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-caban-boucle-rug/displacement.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-caban-boucle-rug/displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-caban-boucle-rug/normal.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-caban-boucle-rug/normal.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-caban-boucle-rug/roughness.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-caban-boucle-rug/roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-cotton-jersey-rug/ao.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-cotton-jersey-rug/ao.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-cotton-jersey-rug/color.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-cotton-jersey-rug/color.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-cotton-jersey-rug/displacement.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-cotton-jersey-rug/displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-cotton-jersey-rug/normal.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-cotton-jersey-rug/normal.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-cotton-jersey-rug/roughness.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-cotton-jersey-rug/roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-floral-jacquard-rug/ao.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-floral-jacquard-rug/ao.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-floral-jacquard-rug/color.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-floral-jacquard-rug/color.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-floral-jacquard-rug/displacement.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-floral-jacquard-rug/displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-floral-jacquard-rug/normal.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-floral-jacquard-rug/normal.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-floral-jacquard-rug/roughness.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-floral-jacquard-rug/roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-gingham-check-round-rug/ao.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-gingham-check-round-rug/ao.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-gingham-check-round-rug/color.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-gingham-check-round-rug/color.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-gingham-check-round-rug/displacement.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-gingham-check-round-rug/displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-gingham-check-round-rug/normal.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-gingham-check-round-rug/normal.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-gingham-check-round-rug/roughness.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-gingham-check-round-rug/roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-herringbone-wool-rug/ao.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-herringbone-wool-rug/ao.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-herringbone-wool-rug/color.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-herringbone-wool-rug/color.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-herringbone-wool-rug/displacement.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-herringbone-wool-rug/displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-herringbone-wool-rug/normal.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-herringbone-wool-rug/normal.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-herringbone-wool-rug/roughness.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-herringbone-wool-rug/roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-quatrefoil-jacquard-rug/color.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-quatrefoil-jacquard-rug/color.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-quatrefoil-jacquard-rug/displacement.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-quatrefoil-jacquard-rug/displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-quatrefoil-jacquard-rug/normal.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-quatrefoil-jacquard-rug/normal.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-quatrefoil-jacquard-rug/roughness.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-quatrefoil-jacquard-rug/roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-rough-linen-runner/ao.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-rough-linen-runner/ao.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-rough-linen-runner/color.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-rough-linen-runner/color.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-rough-linen-runner/displacement.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-rough-linen-runner/displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-rough-linen-runner/normal.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-rough-linen-runner/normal.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-rough-linen-runner/roughness.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-rough-linen-runner/roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-velour-velvet-rug/ao.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-velour-velvet-rug/ao.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-velour-velvet-rug/color.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-velour-velvet-rug/color.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-velour-velvet-rug/displacement.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-velour-velvet-rug/displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-velour-velvet-rug/normal.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-velour-velvet-rug/normal.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-velour-velvet-rug/roughness.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-velour-velvet-rug/roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-wool-boucle-round-rug/ao.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-wool-boucle-round-rug/ao.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-wool-boucle-round-rug/color.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-wool-boucle-round-rug/color.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-wool-boucle-round-rug/displacement.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-wool-boucle-round-rug/displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-wool-boucle-round-rug/normal.png",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-wool-boucle-round-rug/normal.ktx2"
  ],
  [
    "/assets/textures-runtime/rugs/polyhaven-wool-boucle-round-rug/roughness.jpg",
    "/assets/textures-runtime-ktx2/rugs/polyhaven-wool-boucle-round-rug/roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster001/Plaster001_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster001/Plaster001_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster001/Plaster001_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster001/Plaster001_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster001/Plaster001_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster001/Plaster001_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster001/Plaster001_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster001/Plaster001_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster001/Plaster001_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster001/Plaster001_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster002/Plaster002_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster002/Plaster002_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster002/Plaster002_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster002/Plaster002_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster002/Plaster002_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster002/Plaster002_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster002/Plaster002_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster002/Plaster002_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster002/Plaster002_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster002/Plaster002_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster003/Plaster003_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster003/Plaster003_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster003/Plaster003_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster003/Plaster003_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster003/Plaster003_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster003/Plaster003_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster003/Plaster003_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster003/Plaster003_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster003/Plaster003_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster003/Plaster003_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster007/Plaster007_1K-JPG_AmbientOcclusion.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster007/Plaster007_1K-JPG_AmbientOcclusion.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster007/Plaster007_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster007/Plaster007_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster007/Plaster007_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster007/Plaster007_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster007/Plaster007_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster007/Plaster007_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster007/Plaster007_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster007/Plaster007_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Plaster007/Plaster007_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/walls/Plaster007/Plaster007_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper001A/Wallpaper001A_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper001A/Wallpaper001A_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper001A/Wallpaper001A_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper001A/Wallpaper001A_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper001A/Wallpaper001A_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper001A/Wallpaper001A_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper001A/Wallpaper001A_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper001A/Wallpaper001A_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper001A/Wallpaper001A_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper001A/Wallpaper001A_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper001B/Wallpaper001B_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper001B/Wallpaper001B_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper001B/Wallpaper001B_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper001B/Wallpaper001B_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper001B/Wallpaper001B_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper001B/Wallpaper001B_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper001B/Wallpaper001B_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper001B/Wallpaper001B_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper001B/Wallpaper001B_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper001B/Wallpaper001B_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper001C/Wallpaper001C_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper001C/Wallpaper001C_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper001C/Wallpaper001C_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper001C/Wallpaper001C_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper001C/Wallpaper001C_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper001C/Wallpaper001C_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper001C/Wallpaper001C_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper001C/Wallpaper001C_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper001C/Wallpaper001C_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper001C/Wallpaper001C_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper002A/Wallpaper002A_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper002A/Wallpaper002A_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper002A/Wallpaper002A_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper002A/Wallpaper002A_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper002A/Wallpaper002A_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper002A/Wallpaper002A_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper002A/Wallpaper002A_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper002A/Wallpaper002A_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper002A/Wallpaper002A_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper002A/Wallpaper002A_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper002B/Wallpaper002B_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper002B/Wallpaper002B_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper002B/Wallpaper002B_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper002B/Wallpaper002B_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper002B/Wallpaper002B_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper002B/Wallpaper002B_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper002B/Wallpaper002B_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper002B/Wallpaper002B_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper002B/Wallpaper002B_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper002B/Wallpaper002B_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper002C/Wallpaper002C_1K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper002C/Wallpaper002C_1K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper002C/Wallpaper002C_1K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper002C/Wallpaper002C_1K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper002C/Wallpaper002C_1K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper002C/Wallpaper002C_1K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper002C/Wallpaper002C_1K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper002C/Wallpaper002C_1K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/walls/Wallpaper002C/Wallpaper002C_1K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/walls/Wallpaper002C/Wallpaper002C_1K-JPG_Roughness.ktx2"
  ],
  [
    "/assets/textures-runtime/wood-floor-051/WoodFloor051_2K-JPG_AmbientOcclusion.jpg",
    "/assets/textures-runtime-ktx2/wood-floor-051/WoodFloor051_2K-JPG_AmbientOcclusion.ktx2"
  ],
  [
    "/assets/textures-runtime/wood-floor-051/WoodFloor051_2K-JPG_Color.jpg",
    "/assets/textures-runtime-ktx2/wood-floor-051/WoodFloor051_2K-JPG_Color.ktx2"
  ],
  [
    "/assets/textures-runtime/wood-floor-051/WoodFloor051_2K-JPG_Displacement.jpg",
    "/assets/textures-runtime-ktx2/wood-floor-051/WoodFloor051_2K-JPG_Displacement.ktx2"
  ],
  [
    "/assets/textures-runtime/wood-floor-051/WoodFloor051_2K-JPG_NormalDX.jpg",
    "/assets/textures-runtime-ktx2/wood-floor-051/WoodFloor051_2K-JPG_NormalDX.ktx2"
  ],
  [
    "/assets/textures-runtime/wood-floor-051/WoodFloor051_2K-JPG_NormalGL.jpg",
    "/assets/textures-runtime-ktx2/wood-floor-051/WoodFloor051_2K-JPG_NormalGL.ktx2"
  ],
  [
    "/assets/textures-runtime/wood-floor-051/WoodFloor051_2K-JPG_Roughness.jpg",
    "/assets/textures-runtime-ktx2/wood-floor-051/WoodFloor051_2K-JPG_Roughness.ktx2"
  ]
])
